[package]
author = "tomblazejewski <tomi.blazejewski@gmail.com>"
name = "blaze_explorer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ratatui = "0.27.0"
